CREATE DATABASE bookindex;
USE bookindex;

CREATE TABLE isbn (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	isbn BIGINT UNSIGNED NULL,
	title VARCHAR(500) NOT NULL,
	author VARCHAR(500) NOT NULL,
	amazon_result TEXT,
	last_amazon_update DATETIME NOT NULL,
	PRIMARY KEY (id),
	UNIQUE KEY isbn (isbn)
);

ALTER TABLE isbn
	MODIFY isbn VARCHAR(50) NOT NULL;
